import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme/ThemeProvider";
import Navbar from './components/Layout/Navbar'
import Footer from "./components/Layout/Footer";
import { Providers } from "./providers";
import FloatingCartButton from "./components/cart/FloatingCartButton";
import CartModal from "./components/cart/CartModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Robo's Wishlist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          min-h-screen bg-gray-50 text-gray-800
          dark:bg-gray-900 dark:text-gray-100
        `}
      >
        <ThemeProvider>
          <Providers>
            <Navbar />
            {children}
            <Footer />
            
            {/* Cart Components */}
            <CartModal />
            <FloatingCartButton />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}